import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Button from './components/Button'
import Container from './components/Container'
import Navbar from './components/navbar/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar children={undefined} />
        
        
        {children}
        </body>


    </html>
  )
}
